server:
  port: 9092
  servlet:
    context-path: '/data-converter/'

spring:
  application:
    name: data-export-converter
    dateformatter: "yyyy-MM-dd HH:mm:ss"
  output:
    ansi:
      enabled: Always
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS"
    write-dates-as-timestamps: false
  logging:
    level:
      br.com.brunogodoif: TRACE
      root: INFO
      org:
        springframework:
          web: DEBUG
          jdbc:
            core:
              JdbcTemplate:DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: trace
  kafka:
    bootstrap-servers: localhost:9095

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics