server:
  port: 80

spring:
  application:
    name: data-export-gateway

  cloud:
    gateway:
      routes:
        - id: data-storage
          uri: http://localhost:9091/
          predicates:
            - Path=/data-storage/**
        - id: data-converter
          uri: http://localhost:9092/
          predicates:
            - Path=/data-converter/**

